disabled_rules:
- identifier_name
- trailing_whitespace
line_length:
- 150
- 200
#- ignores_function_declarations: true
#- ignores_comments: true
#- ignores_interpolated_strings: true
#- ignores_urls: true
